# REUSE licensing information association file
#
# References:
#
# * REUSE.toml | REUSE Specification – Version 3.2 | REUSE
#   https://reuse.software/spec-3.2/#reusetoml
#
# Copyright 2026 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+

version = 1

[[annotations]]
path = [
    "*.README.md",
    "**/README.md",
    "snap/local/screenshots/*.png",
    "snap/local/screenshots/*.jpg"
]
SPDX-FileCopyrightText = '2026 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>'
SPDX-License-Identifier = 'CC-BY-SA-4.0+'

[[annotations]]
path = [
    "snap/gui/prime95.png"
]
SPDX-FileCopyrightText = '2024 Prime95 copyright holders <https://www.mersenne.org/>'
SPDX-License-Identifier = 'LicenseRef-FairUse'
